### ISSUE TITLE
パスワード入力欄を半角英数字のみに制限してほしい

### ISSUE THREAD

**Issue by swd-dayodayo** [rikutons/web-tabloiid#3]
アップロード時のパスワードを英数字のみに制限してほしいです～～
https://qiita.com/ka215/items/795a179041c705bef03b

**Comment by rikutons** [comment]
作業ブランチ : password-regulation

**Comment by rikutons** [comment]
https://github.com/rikutons/web-tabloiid/issues/9 に関連するためその実装を待ちます.
