### ISSUE TITLE
ファイルのドラッグアンドドロップ機能実装

### ISSUE THREAD

**Issue by swd-dayodayo** [rikutons/web-tabloiid#6]
記事は古いですが生JSだけでも実現可能ぽいです
https://koheik.hatenablog.com/entry/2016/07/08/152936

**Comment by rikutons** [comment]
作業ブランチ upload-with-drag-and-drop

**Comment by rikutons** [comment]
Railsでこの記事を参考にJSを使用: 
https://nobunobu1717.site/?p=1292
