### ISSUE TITLE
一覧画面の４つ横並び２段表示について

### ISSUE THREAD

**Issue by swd-dayodayo** [rikutons/web-tabloiid#7]
flexBox

**Comment by swd-dayodayo** [comment]
ＰＤＦをアップロードすべき場所に画像やテキストといった別拡張子のファイルも選択できてしまう。
今回編集画面を用意してないので事前にＰＤＦで絞り込んだほうがよさそう

**Comment by rikutons** [comment]
https://liginc.co.jp/web/html-css/css/21024
flexboxチュートリアルのおすすめサイトを共有しておきます.

**Comment by swd-dayodayo** [comment]
https://www.webcreatorbox.com/tech/object-fit
